openapi: 3.0.0
info:
  title: 'Hello World API'
  version: 0.1.0
paths:
  /clients:
    get:
      tags:
        - Client
      summary: 'Retrieves Client collection resource.'
      responses:
        '200':
          description: 'The Client collection resource.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: array, items: { $ref: '#/components/schemas/Client' } }
                type: object
    post:
      tags:
        - Client
      summary: 'Inserts new Client item into collection resource.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: 'Inserted Client resource IRI.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, example: { '@id': /clients/1 } }
                type: object
        '400':
          description: 'Bad request.'
  '/clients/{id}':
    get:
      tags:
        - Client
      summary: 'Retrieves given Client resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'The Client resource.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, $ref: '#/components/schemas/Client' }
                type: object
        '404':
          description: 'Resource not found.'
    put:
      tags:
        - Client
      summary: 'Replaces given Client resource with new one.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: 'Replaced Client resource IRI.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, example: { '@id': /clients/1 } }
                type: object
        '400':
          description: 'Bad request.'
        '404':
          description: 'Resource not found.'
    delete:
      tags:
        - Client
      summary: 'Removes given Client resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'The Client resource is removed.'
        '404':
          description: 'Resource not found.'
  '/clients/{id}/transactions':
    get:
      tags:
        - Client
      summary: 'Retrieves Transaction collection resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'The Transaction collection resource.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: array, items: { $ref: '#/components/schemas/Transaction' } }
                type: object
    post:
      tags:
        - Client
      summary: 'Inserts new Transaction item into collection resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: 'Inserted Transaction resource IRI.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, example: { '@id': /transactions/1 } }
                type: object
        '400':
          description: 'Bad request.'
  '/transactions/{id}':
    get:
      tags:
        - Transaction
      summary: 'Retrieves given Transaction resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'The Transaction resource.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, $ref: '#/components/schemas/Transaction' }
                type: object
        '404':
          description: 'Resource not found.'
    put:
      tags:
        - Transaction
      summary: 'Replaces given Transaction resource with new one.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: 'Replaced Transaction resource IRI.'
          content:
            application/json:
              schema:
                properties:
                  data: { type: object, example: { '@id': /transactions/1 } }
                type: object
        '400':
          description: 'Bad request.'
        '404':
          description: 'Resource not found.'
    delete:
      tags:
        - Transaction
      summary: 'Removes given Transaction resource.'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'The Transaction resource is removed.'
        '404':
          description: 'Resource not found.'
components:
  schemas:
    Client:
      properties:
        id:
          type: integer
          readOnly: true
          example: '1'
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        email:
          type: string
          example: john@doe.com
        transactions:
          description: Transaction>
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
      type: object
    Transaction:
      properties:
        id:
          type: string
          readOnly: true
          example: XYZ
        title:
          type: string
          example: 'Purchase 123'
        client:
          type: object
          $ref: '#/components/schemas/Client'
      type: object
