services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    public: false       # Allows optimizing the container by removing unused services; this also means
                        # fetching services directly from the container via $container->get() won't work.
                        # The best practice is to be explicit about your dependencies anyway.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude:
      - '../src/Domain'

  # make resources and operations accessible from container
  # as they can be loaded in runtime by Gorynych
  App\Application\Resource\:
    resource: '../src/Application/Resource'
    public: true

  App\Ports\Operation\:
    resource: '../src/Ports/Operation'
    public: true

  entity_manager.adapter:
    class: App\Infrastructure\Adapter\EntityManagerAdapter
    public: true

  Gorynych\Adapter\EntityManagerAdapterInterface: '@App\Infrastructure\Adapter\EntityManagerAdapter'
