name: API tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup test environment
      run: cp .env.test.dist .env.test && (mkdir var/sqlite)

    - name: Run API functional tests
      run: ./vendor/bin/phpunit
